//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("4.6.9.0")]
[assembly: AssemblyVersion("4.6.9.0")]
[assembly: AssemblyInformationalVersion("4.6.9-Adaptive-Rest.11+Branch.Adaptive-Rest.Sha.33bef312cbe591ec20a605b542c227530fd6b9de")]